### ISSUE TITLE
Update LandfireLatLongBox to produce expected map shapes from H, W

### ISSUE THREAD

**Issue by afennelly-mitre** [mitrefireline/simfire#17]
# Investigate behavior of different operational locations

## Summary

From the perspective of SimHarness, we would like to be able to train (and evaluate) on multiple operational locations in a given experiment. However, it is currently unclear how to configure the `operational` settings of the simfire config to ensure a resulting map size of shape `(X, Y)`. When it comes to the RL training aspect, we must ensure that the map size is consistent across operational locations. The batches used for training are constructed from samples in the respective environments, and we have a predefined observation space that the arrays must "fit" into. For example, if train location A has fire map shape `(121, 121)` and train location B has fire map shape `(129, 130)`, the current training code will fail.

- We know that the main fields of importance are the `latitude`, `longitude`, `height`, and `width`. 
  1. If we fix the `latitude` and `longitude`, but change the `height` and `width`, the resulting map sizes will be different.
  2. If we fix the `height` and `width`, but change the `latitude` and `longitude`, the resulting map sizes _may_ differ. The important thing is we can't guarantee that fixed H,W results in same map size across operational locations.

Addressing 1. isn't urgent wrt SimHarness, as we want multiple operational locations, not multiple map sizes for the same location. However, I believe it is crucial to understand this behavior in order to eventually scale up the map sizes used for training (and evaluation).

Addressing 2. is crucial for training on multiple operational locations!

## Steps to reproduce (using simfire `v1.5.8`)

<details>

<summary>
Example: Vary height and width
</summary>

Say we choose to use the following location from the BurnMD dataset:
```shell
BurnMDOperationalLocation(uid='Oregon_2020_242', latitude=42.68383321400006, longitude=-121.96376057099997)
```

To use this location, we can set the `operational` section in the simfire config with:
```yaml
operational:
  seed:
  latitude: 42.68383321400006 # top left corner
  longitude: -121.96376057099997 # top left corner
  height: 5000
  width: 5000
  resolution: 30
  year: 2019
```

Using the above config, we get a resulting screen size of `(121, 121)` - get this via `sim.fire_map.shape`, `sim.terrain.topo_layer.data.shape`, `sim.terrain.fuels.shape`, etc.

Now change `height` and `width` from `5000` to `6000`. The resulting screen size is `(145, 145)`.

</details>

<details>

<summary>
Example: Vary longitude and latitude
</summary>

Say we choose to use the following 2 locations from the BurnMD dataset:
```shell
loc_A = BurnMDOperationalLocation(uid='Oregon_2020_242', latitude=42.68383321400006, longitude=-121.96376057099997)
loc_b = BurnMDOperationalLocation(uid='Wyoming_2019_Fishhawk', latitude=44.44007334400004, longitude=-109.89815622099997)
```

To use `loc_A`, we can set the `operational` section in the simfire config with:
```yaml
operational:
  seed:
  latitude: 42.68383321400006 # top left corner
  longitude: -121.96376057099997 # top left corner
  height: 5000
  width: 5000
  resolution: 30
  year: 2019
```

Using the above config, we get a resulting screen size of `(121, 121)` - get this via `sim.fire_map.shape`, `sim.terrain.topo_layer.data.shape`, `sim.terrain.fuels.shape`, etc.

To use `loc_B`, we can set the `operational` section in the simfire config with:
```yaml
operational:
  seed:
  latitude: 44.44007334400004 # top left corner
  longitude: -109.89815622099997 # top left corner
  height: 5000
  width: 5000
  resolution: 30
  year: 2019
```

Using the above config, we get a resulting screen size of `(129, 130)`.

</details>

 ## Possible fixes

From the perspective of SimHarness:

**Option A**: Take all the operational locations used for training (evaluation), and get the minimum fire map size across all training (evaluation) locations. Then, crop observations to the "smallest" size before returning from `step()` and `reset()`. I'm not sure if this is the best approach, but it's a start. We would need to be clever with the cropping strategy, ie. don't crop out the fire, etc.

**Option B**: We could try to "pad" the smaller maps to the size of the largest map. The tricky piece here is that we would want to set the values to "make sense" in the context of the fire map and respective data layers. But, if the total number of "padded" squares is small, this may not be a huge issue.
